#! /bin/bash
# Download dotfiles and corresponding plugin managers
# credits: https://www.atlassian.com/git/tutorials/dotfiles

DOTFILES_DIRECTORY="${HOME}/.local/share/dotfiles"
DOTFILES_BACKUP_DIRECTORY="${HOME}/.config-backup"

# zinit - zsh plugin manager
sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
# dein - vim plugin manager
curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh \
    | sh -s '/home/coma/.local/share/dein'
# tpm - tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# My dotfiles
git clone --bare 'https://github.com/coma64/dotfiles' "${DOTFILES_DIRECTORY}"

err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
}

config() {
    git --git-dir="${DOTFILES_DIRECTORY}" --work-tree="${HOME}" "$@"
}

backup_file() {
    mkdir --parents "$(dirname "${BACKUP_DIRECTORY}/$1")"
    mv "$1" "${BACKUP_DIRECTORY}/$1"
}

if config checkout "$1"; then
    echo 'Checked out config.';
else
    echo 'Backing up pre-existing dotfiles to ~/.config-backup';

    mkdir -p "${BACKUP_DIRECTORY}"

    export -f backup_file
    export DOTFILES_DIRECTORY, DOTFILES_BACKUP_DIRECTORY
    config checkout "$1" 2>&1 \
        | grep '\s+\.' \
        | awk '{ print $1 }' \
        | xargs -I '{}' bash -c "backup_file '{}' && echo 'Backing up {}'"
fi

if config checkout "$1"; then
    config config status.showUntrackedFiles no
else
    err 'Failed installing dotfiles'
fi
